services:
  postgres:
    image: postgres
    container_name: studio_share_postgres
    command: postgres -c 'max_connections=200'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: mnmr1996development
      POSTGRES_PASSWORD: mnmr1996development
      POSTGRES_DB: studio_share
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - studio_share_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mnmr1996development -d studio_share" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  pgadmin:
    container_name: studio_share_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - studio_share_network



networks:
  studio_share_network:

volumes:
  pgadmin:
