services:
  # postgres data base
  postgres:
    container_name: studio_share_pg
    image: postgres
    environment:
      POSTGRES_DB: studio_share
      POSTGRES_USER: mnmr1996development
      POSTGRES_PASSWORD: mnmr1996development
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mnmr1996development -d art_share" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    # for pgadmin
  pgadmin:
    container_name: studio_share_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      microservices-net:
    restart: unless-stopped

  mongodb:
    container_name: studio_share_mongo_db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mnmr1996development
      MONGO_INITDB_ROOT_PASSWORD: mnmr1996development

  mongo-express:
    image: mongo-express
    container_name: studio_share_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mnmr1996development
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mnmr1996development
      - ME_CONFIG_MONGODB_SEVER=mongodb



networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: